[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'nightsense/strawberry'
hook_add = '''
  set background=light
  au MyAutoCmd VimEnter * nested colorscheme strawberry-light
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
