[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'nightsense/strawberry'
hook_add = '''
  set background=light
  au MyAutoCmd VimEnter * nested colorscheme strawberry-light
  au MyAutoCmd VimEnter * nested highlight Normal ctermbg=NONE guibg=NONE
  au MyAutoCmd VimEnter * nested highlight NonText ctermbg=NONE guibg=NONE
  au MyAutoCmd VimEnter * nested highlight SpecialKey ctermbg=NONE guibg=NONE
  au MyAutoCmd VimEnter * nested highlight EndOfBuffer ctermbg=NONE guibg=NONE
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
